# 资助信息（可选）
# 如果您希望接受赞助，可以配置以下平台

# GitHub Sponsors
# github: [your-github-username]

# Patreon
# patreon: your-patreon-username

# Open Collective
# open_collective: your-project-name

# Ko-fi
# ko_fi: your-kofi-username

# 自定义链接
# custom: ["https://your-donation-link.com"]
